### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by stevepop** [vaso2/nuxt-fontawesome#8]
I just installed this package and I am getting the following warnings;
```
warning @fortawesome/fontawesome@1.1.8: This package is deprecated. See https://git.io/fNCzJ for information about upgrading.
warning @fortawesome/fontawesome-free-brands@5.0.13: This package is deprecated. See https://git.io/fNCzJ for information about upgrading.
warning @fortawesome/fontawesome-free-solid@5.0.13: This package is deprecated. See https://git.io/fNCzJ for information about upgrading.
```
Is there any fix for this?

Thanks for your efforts!

**Comment by vaso2** [comment]
Hi there! 
You should do exactly as recommended in your [warning message](https://git.io/fNCzJ), and update your dependencies
Issue is not related to this package, it's Fontawesome itself, so now you should use 
`@fortawesome/free-solid-svg-icons` instead of `@fortawesome/fontawesome-free-solid` etc.
For example, current versions in **nuxt-fontawesome**'s `package.json` is 
```
"dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.12",
    "@fortawesome/vue-fontawesome": "^0.1.4"
  },
  "devDependencies": {
    "@fortawesome/free-solid-svg-icons": "^5.6.3",
    "@fortawesome/free-brands-svg-icons": "^5.6.3"
  }
```
Cheers!
